#!/bin/sh

set -e
PATH="/usr/local/bin:$PATH"
if [ "$(git rev-parse --is-inside-work-tree)"='true' ]; then

  gitdir="$(git rev-parse --git-dir)"
  dir="$(git rev-parse --git-common-dir)"

elif [ "$(git rev-parse --is-inside-git-dir)"='true' ]; then

  gitdir="$(git rev-parse --git-dir)"
  dir="$gitdir"

else
  echo 'Not inside a git repo, bailing' >&2
  exit 1
fi
trap 'rm -f "$dir/$$.tags"' EXIT

if [ -f "$dir/.ctags-ignore" ]; then
  ignorepath="$dir/.ctags-ignore"
else
  ignorepath="$gitdir/.ctags-ignore"
fi

uuid=$(uuidgen)
echo "$uuid" > "$dir/taglock"

sleep 1

if [ -f "$dir/taglock" -a  $(cat "$dir/taglock") = "$uuid" ]; then

  ([ -f "$ignorepath" ] && git ls-files | grep -E -v -f "$ignorepath" || git ls-files) | \
    ctags --tag-relative -L - -f"$dir/$$.tags"

  mv "$dir/$$.tags" "$dir/tags"

  rm -f "$dir/taglock"

fi &
