#!/bin/sh

set -e
PATH="/usr/local/bin:$PATH"
if [ "$(git rev-parse --is-inside-work-tree)"='true' ]; then
  dir="$(git rev-parse --git-common-dir)"
elif [ "$(git rev-parse --is-inside-git-dir)"='true' ]; then
  dir="$(git rev-parse --git-dir)"
else
  echo 'Not inside a git repo, bailing' >&2
  exit 1
fi
trap 'rm -f "$dir/$$.tags"' EXIT

ignorepath="$dir/.ctags-ignore"

uuid=$(uuidgen)
echo "$uuid" > "$dir/taglock"

sleep 1

if [ -f "$dir/taglock" -a  $(cat "$dir/taglock") = "$uuid" ]; then

  ([ -f "$ignorepath" ] && git ls-files | grep -E -v -f "$ignorepath" || git ls-files) | \
    ctags --tag-relative -L - -f"$dir/$$.tags"

  mv "$dir/$$.tags" "$dir/tags"

  rm -f "$dir/taglock"

fi &
