#!/bin/sh

set -e
PATH="/usr/local/bin:$PATH"
if [ "$(git rev-parse --is-inside-work-tree)"='true' ]; then

  gitdir="$(git rev-parse --git-dir)"
  commondir="$(git rev-parse --git-common-dir)"

elif [ "$(git rev-parse --is-inside-git-dir)"='true' ]; then

  gitdir="$(git rev-parse --git-dir)"
  commondir="$gitdir"

else
  echo 'Not inside a git repo, bailing' >&2
  exit 1
fi

tagspath="$gitdir/tags"

if [ $(($(date +%s) - $(stat -L --format %Y "$tagspath"))) -lt 10 ]; then
  # Modified recently, skipping...
  exit 1
fi

trap 'rm -f "$gitdir/$$.tags"' EXIT

if [ -f "$gitdir/.ctags-ignore" ]; then
  ignorepath="$gitdir/.ctags-ignore"
else
  ignorepath="$commondir/.ctags-ignore"
fi

uuid=$(uuidgen)
echo "$uuid" > "$gitdir/taglock"

sleep 1

if [ -f "$gitdir/taglock" -a  $(cat "$gitdir/taglock") = "$uuid" ]; then

  ([ -f "$ignorepath" ] && git ls-files | grep -E -v -f "$ignorepath" || git ls-files) | \
    ctags --tag-relative -L - -f"$gitdir/$$.tags"

  mv "$gitdir/$$.tags" "$tagspath"

  rm -f "$gitdir/taglock"

fi &
