#!/bin/bash

target="$1"
if [ -z "$builtin" ]; then
  builtin="eDP1"
fi
builtin_mode="1600x900_60.00"

touchscreen_id=$(xinput list --id-only 'Atmel Atmel maXTouch Digitizer')

if [ -z "$target" ]; then
  target="$(xrandr | grep '\(dis\)\?connected' | grep -v 'disconnected' | grep -v "$builtin" | cut -f 1 -d ' ')"
fi

echo "Using $target"

after_display_config() {
  xinput --map-to-output "$touchscreen_id" "$builtin"
}
