#!/usr/bin/env python

import sys
import optparse
op = optparse.OptionParser()
op.add_option('-b', '--backwards', dest='direction', help="Cycle backwards through the list",
              action="store_const", const=-1, default=1)
(options,args) = op.parse_args()

current = None if not args else args[0]

lines = sys.stdin.read().strip().split('\n')

if current and current in lines:
  idx = lines.index(current)
elif options.direction > 0:
  idx = -1
else:
  idx = 0

idx=(idx + options.direction + len(lines)) % len(lines)
print lines[idx]
