#!/usr/bin/env bash

greppattern="$1"
regex="$2"
namefilter="$3"

git grep --name-only -P "$greppattern" -- "$namefilter" | while read path; do
  perl -ne "$regex; print" < "$path" | sponge "$path"
done
