#!/bin/sh

if type xclip >/dev/null 2>&1 && [ -n "$DISPLAY" ]; then
  XCLIP_IN="xclip -i";
  XCLIP_OUT="xclip -o";
elif type pbcopy >/dev/null 2>&1; then
  XCLIP_IN="pbcopy";
  XCLIP_OUT="pbpaste";
else
  unset XCLIP_IN
  unset XCLIP_OUT
fi

if type xdg-open >/dev/null 2>&1 && [ -n "$DISPLAY" ]; then
  OPEN="xdg-open"
elif type open >/dev/null 2>&1; then
  OPEN="open"
fi

line=$(git remote -v show -n origin | grep 'Fetch URL')

if [[ $line == *"github.com"* ]]; then
  skipstr='  Fetch URL: git@github.com:'
  skip=${#skipstr}
  length=$((${#line}-$skip-4))
  repopath=${line:skip:$length} # "account/repo"
  branchname=$(git name-rev HEAD)
  branchname=${branchname:5}

  url="https://github.com/$repopath/tree/$branchname"
fi

if [ "$1" = "-n" ]; then
  echo "$url"
elif [ "$1" = "-c" ]; then
  echo "$url\c" | $XCLIP_IN && echo "Copied to clipboard"
else
  $OPEN "$url"
fi
