#!/bin/sh

gitroot="$(git-root)"
shapath="$gitroot/.git/rebase-merge/stopped-sha"

if [ ! -d "$gitroot" ]; then
  if [ -e "$shapath" ]; then
    git show $(cat "$shapath")
  else
    echo "No conflicts"
  fi
fi
