#!/bin/sh

target="$1"

if [ "x$target" = "x" ]; then
  target="$(xrandr | grep '\(dis\)\?connected' | grep -v 'disconnected' | grep -v eDP1 | cut -f 1 -d ' ')"
fi

echo "Using $target"

xrandr --output "$target" --above eDP1 --auto
