#!/bin/sh

target="$1"

if [ "x$target" = "x" ]; then
  target="$(xrandr | grep '\(dis\)\?connected' | grep -v 'disconnected' | grep -v eDP1 | cut -f 1 -d ' ')"
fi

echo "Using $target"
touchscreen_id=$(xinput list --id-only 'Atmel Atmel maXTouch Digitizer')

xrandr --output $target --off
xinput --map-to-output "$touchscreen_id" eDP1
