#!/bin/sh

# Probably a good idea to stick this in /etc/udev/rules.d somewhere
# SUBSYSTEM=="leds", RUN+="/bin/chmod 0664 %S%p/brightness", RUN+="/bin/chgrp plugdev %S%p/brightness"

root="/sys/class/leds/asus::kbd_backlight"

device="$root/brightness"

cur="$(cat "$device")"

min=0
max="$(cat "$root/max_brightness")"

if [ "$cur" -gt "$min" ]; then
  tgt=$(($cur-1))

  echo "$cur -> $tgt"
  echo -n "$tgt" > "$device"
else
  echo "min"
fi
