#!/bin/bash

# Simple wrapper to make working with local node package repos easier.
# Usage:
#   $ npm install http-server # Install to a local repo
#   $ np http-server -p 8080  # Use the locally provided binary

if [ ! -d node_modules ]; then
    echo 'Unable to find a functional node_modules in the current directory!'
    echo 'Usage: np command [args...]'
    exit 1
fi

if [ -f "package.json" ] && hash jq; then
    if [ -d "$HOME/.nvm" ] && [ ! -z "$NVM_DIR" ]; then
        [ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"

        nodeVersion="$(jq -cMr '.engines.node' < package.json)"
        nvm use "$nodeVersion"
    fi
fi

export NODE_PATH="$(pwd)/node_modules"
export PATH="$(pwd)/node_modules/.bin:$PATH"

"$@"
