#!/bin/sh

card=$(cat ~/.config/local/pulse-soundcard)

card=$(pactl list sinks short | cut -f 2 | cycle             "$card" | tee ~/.config/local/pulse-soundcard)
echo $card
pacmd set-default-sink "$card"
