#!/bin/bash

session=vocities
keyfile=blast-zenbook
dir=~/Projects/vocities/vocities
dockerdeps=(vocities-postgres vocities-redis)
windows=(sbt:1 vim:2 shell:3 redis:7 psql:9)
commands=(sbt:sbt vim:vim-recover)

tmux_after() {
    until nc -z localhost 6379; do
        echo 'waiting for localhost:6379 (redis)'
        sleep 1
    done
    tmux send-keys -t "${session}:redis" $'redis-cli\n'

    until nc -z localhost 5432; do
        echo 'waiting for localhost:5432 (postgres)'
        sleep 1
    done
    sleep 1 # Give pg an additional second after the socket opens to actually start accepting connections
    tmux send-keys -t "${session}:psql" $'psql --user postgres -h localhost vocities\n'
}

source _tmux_start-session
