#!/bin/bash

session=work
keyfile=talenthouse
dir=~/Work/Talenthouse/th-public
dockerdeps=(th-postgres th-rabbitmq th-redis th-elasticsearch)
windows=(sbt:1 vim:2 shell:3 redis:7 gulp:8 psql:9)
commands=(sbt:sbt vim:vim-recover redis:redis-cli gulp:'np gulp watch')

tmux_after() {
    until nc -z localhost 5432; do
        echo 'waiting for localhost:5432 (postgres)'
        sleep 1
    done
    sleep 1 # Give pg an additional second after the socket opens to actually start accepting connections
    tmux send-keys -t "${session}:psql" $'psql --user postgres -h localhost talenthouse\n'
}

source "$(which _tmux_start-session)"
